version: '3'

services:
  mongodb:
    image: mongo:4.2.6
    ports:
      - "27017:27017"
  jmeter-example-service:
    build: ./jmeter-example-service
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
